spring.datasource.url=jdbc:postgresql://localhost:5432/AppBombero
spring.datasource.username=postgres
spring.datasource.password=0099

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL10Dialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG

server.address=0.0.0.0
server.port=8081